set packpath^=~/dotfiles/vim

syntax enable

" Basic settings

filetype plugin indent on
set encoding=utf-8
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smarttab
set number
set showcmd
set cursorline
set lazyredraw
set showmatch
set ruler
set incsearch
set hlsearch
set autoread
set scrolloff=5
set visualbell
set backspace=indent,eol,start
set wrap
set linebreak
set relativenumber

" Mappings test

let mapleader=","
inoremap jk <ESC>
nnoremap <leader>ev :vsp ~/dotfiles/vim/vimrc<CR>
nnoremap <leader><space> :nohlsearch<CR>
inoremap {<CR> {<CR>}<C-o>O

" CtrlP settings
let g:ctrlp_match_window='bottom,order:ttb'
let g:ctrlp_switch_buffer=0
let g:ctrlp_working_path_mode=0

" Training wheels

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
inoremap <ESC> <nop>
