" Vimrc
"
" This file contains the minimal settings to set the foundation, with the
" majority of the configuration and settings living in files spread between
" vim/rcfiles and vim/rcplugins

set nocompatible

" Need to set the leader before defining any leader mappings
let mapleader = "\<Space>"

function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/dotfiles/vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
      execute 'source' config_file
    endif
  endfor
endfunction

call plug#begin('~/.vim/plugged')
call s:SourceConfigFilesIn('rcplugins')
call plug#end()


" General Vim Settings
" --------------------

filetype plugin indent on
set encoding=utf-8
syntax enable

set backspace=2  " backspace works like most programs in insert mode
set history=1000
set ruler        " show the cursor position at all times
set showcmd      " display incomplete commands
set incsearch    " incremental searching
set hlsearch     " highlight all search matches
set cursorline
set lazyredraw   " no screen redraw while executing macros
set autoread
set autowrite    " auto write contents of file before running commands
set scrolloff=5
set visualbell   " use visual bell instead of beeping
set wrap         " wrap lines longer than window

" Tabs and Indentation
set tabstop=2
set shiftwidth=2
set shiftround    " round indent to multiple of shiftwidth
set expandtab     " use correct number of spaces for tab in insert mode
set softtabstop=2
set smarttab      " tab in front of line inserts blanks according to shiftwidth
set autoindent    " copy indent from current line when starting new line

" Relative line numbers, absolute current line
set number
set relativenumber

" Mappings test

inoremap jk <ESC>
nnoremap <leader>ev :vsp ~/dotfiles/vim/vimrc<CR>
nnoremap <leader><space> :nohlsearch<CR>
inoremap {<CR> {<CR>}<C-o>O<tab>

" Training wheels

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
inoremap <ESC> <nop>
